/**
 * Canonical lowercase French voie-type vocabulary used to seed `voie_types.code`.
 * Source: official list provided in the project's domain spec (Q6 grilling session).
 * Multi-word types are stored verbatim with a single space separator.
 */
export const VOIE_TYPE_CODES = [
  "abbaye",
  "agglomération",
  "aire",
  "aires",
  "allée",
  "allées",
  "ancien chemin",
  "ancienne route",
  "anciennes routes",
  "anciens chemins",
  "anse",
  "arcade",
  "arcades",
  "autoroute",
  "avenue",
  "barriere",
  "barrieres",
  "bas chemin",
  "bastide",
  "bastion",
  "beguinage",
  "béguinages",
  "berge",
  "berges",
  "bois",
  "boucle",
  "boulevard",
  "bourg",
  "butte",
  "cale",
  "camp",
  "campagne",
  "camping",
  "carre",
  "carreau",
  "carrefour",
  "carrière",
  "carrières",
  "castel",
  "cavée",
  "central",
  "centre",
  "centre commercial",
  "chalet",
  "chapelle",
  "charmille",
  "château",
  "chaussée",
  "chaussées",
  "chemin",
  "chemin vicinal",
  "cheminement",
  "cheminements",
  "chemins",
  "chemins vicinaux",
  "chez",
  "cite",
  "cites",
  "cloître",
  "clos",
  "col",
  "colline",
  "collines",
  "contour",
  "corniche",
  "corniches",
  "cote",
  "côteau",
  "cottage",
  "cottages",
  "cour",
  "cours",
  "darse",
  "degré",
  "degrés",
  "descente",
  "descentes",
  "digue",
  "digues",
  "domaine",
  "domaines",
  "écluse",
  "écluses",
  "église",
  "enceinte",
  "enclave",
  "enclos",
  "escalier",
  "escaliers",
  "espace",
  "esplanade",
  "esplanades",
  "étang",
  "faubourg",
  "ferme",
  "fermes",
  "fontaine",
  "fort",
  "forum",
  "fosse",
  "fosses",
  "foyer",
  "galerie",
  "galeries",
  "gare",
  "garenne",
  "grand boulevard",
  "grand ensemble",
  "grand rue",
  "grande rue",
  "grandes rues",
  "grands ensembles",
  "grille",
  "grimpette",
  "groupe",
  "groupement",
  "groupes",
  "halle",
  "halles",
  "hameau",
  "hameaux",
  "haut chemin",
  "hauts chemins",
  "hippodrome",
  "hlm",
  "île",
  "immeuble",
  "immeubles",
  "impasse",
  "impasses",
  "jardin",
  "jardins",
  "jetee",
  "jetees",
  "levée",
  "lieu dit",
  "lotissement",
  "lotissements",
  "mail",
  "maison forestière",
  "manoir",
  "marche",
  "marches",
  "mas",
  "métro",
  "montée",
  "montees",
  "moulin",
  "moulins",
  "musée",
  "nouvelle route",
  "palais",
  "parc",
  "parcs",
  "parking",
  "parvis",
  "passage",
  "passage à niveau",
  "passe",
  "passerelle",
  "passerelles",
  "passes",
  "patio",
  "pavillon",
  "pavillons",
  "péripherique",
  "péristyle",
  "petit chemin",
  "petite allée",
  "petite avenue",
  "petite impasse",
  "petite route",
  "petite rue",
  "petites allées",
  "place",
  "placis",
  "plage",
  "plages",
  "plaine",
  "plan",
  "plateau",
  "plateaux",
  "pointe",
  "pont",
  "ponts",
  "porche",
  "port",
  "porte",
  "portique",
  "portiques",
  "poterne",
  "pourtour",
  "pré",
  "presqu'île",
  "promenade",
  "quai",
  "quartier",
  "raccourci",
  "raidillon",
  "rampe",
  "rempart",
  "résidence",
  "résidences",
  "roc",
  "rocade",
  "rond point",
  "roquet",
  "rotonde",
  "route",
  "routes",
  "rue",
  "ruelle",
  "ruelles",
  "rues",
  "sente",
  "sentes",
  "sentier",
  "sentiers",
  "square",
  "stade",
  "station",
  "terrain",
  "terrasse",
  "terrasses",
  "terre plein",
  "tertre",
  "tertres",
  "tour",
  "traverse",
  "val",
  "vallée",
  "vallon",
  "venelle",
  "venelles",
  "via",
  "vieille route",
  "vieux chemin",
  "villa",
  "village",
  "villages",
  "villas",
  "voie",
  "voies",
  "zone",
  "zone industrielle",
  "zone à urbaniser en priorité",
  "zone artisanale",
  "zone d'activité",
  "zone d'amenagement concerté",
  "zone d'amenagement differé",
] as const;

export type VoieTypeCode = (typeof VOIE_TYPE_CODES)[number];
